# Generated by Django 4.0 on 2021-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FLOOR', models.IntegerField()),
                ('UNIT_TYPE', models.CharField(max_length=15)),
                ('UNIT', models.IntegerField()),
                ('INTERIOR', models.IntegerField()),
                ('TERRACE', models.IntegerField()),
                ('TOTAL', models.IntegerField()),
                ('PRICE', models.IntegerField()),
                ('FLOOR_PLANE', models.FileField(upload_to='floor_plane/')),
            ],
        ),
    ]
