# Generated by Django 4.0 on 2021-12-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='INTERIOR',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='TERRACE',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='TOTAL',
            field=models.CharField(max_length=25),
        ),
    ]
