# Generated by Django 4.0 on 2021-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_listing_interior_alter_listing_terrace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='BATHROOMS',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='FLOOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='INTERIOR',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='PRICE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='TERRACE',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='TOTAL',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='UNIT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='UNIT_TYPE',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
