# Generated by Django 4.0 on 2021-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_bathrooms_alter_listing_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='FLOOR_PLANE',
            field=models.FileField(blank=True, upload_to='floor_plane/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='PRICE',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
